server:
  port: 8080

account:
  baseUrl: http://localhost:8083

spring:
  kafka:
    bootstrap-servers: localhost:19092
    listener:
      concurrency: 3
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    properties:
      spring.json.add.type.headers: false
